# Generated by Django 5.0.6 on 2024-06-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                (
                    "referrer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Бизнес пользователи",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=155, verbose_name="Регион")),
                (
                    "pansionat",
                    models.CharField(max_length=155, verbose_name="Пансионат"),
                ),
                (
                    "type_accommodation",
                    models.CharField(max_length=155, verbose_name="Тип размещение"),
                ),
                (
                    "facilities",
                    models.CharField(max_length=155, verbose_name="Удобства"),
                ),
                (
                    "quantities",
                    models.CharField(max_length=155, verbose_name="Количества"),
                ),
                ("price", models.CharField(max_length=155, verbose_name="Цена")),
                (
                    "phone_number",
                    models.CharField(max_length=155, verbose_name="Номер телефона"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен!"),
                ),
                (
                    "referrer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram.userbusiness",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Бизнес",
            },
        ),
    ]
