# Generated by Django 5.0.6 on 2024-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="photos",
            field=models.TextField(default=1, verbose_name="Фотографии"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="business",
            name="type_accommodation",
            field=models.CharField(max_length=155, verbose_name="Тип размещения"),
        ),
    ]
