# Generated by Django 5.0.6 on 2024-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram", "0002_business_photos_alter_business_type_accommodation"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCklient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="Айди")),
                (
                    "referrer_id",
                    models.CharField(max_length=100, verbose_name="Айди Реферальки"),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Имя пользователя"),
                ),
            ],
            options={
                "verbose_name_plural": "Пользователи клиента",
            },
        ),
        migrations.AddField(
            model_name="userbusiness",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
