# Generated by Django 5.0.6 on 2024-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_cklient_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cklient',
            name='comment',
            field=models.TextField(verbose_name='Комментраия'),
        ),
    ]
